Repository SandroMaglione/fpdart, pull requests merged in 2023-02, with the labels that each got.

#86 Upgrade dependencies
  example/json_serializable/pubspec.lock
  example/open_meteo_api/pubspec.lock
  example/pokeapi_functional/pubspec.lock
  example/read_write_file/pubspec.lock
  pubspec.lock
  pubspec.yaml
Labels: chore

#78 add example "managing_imports"
  example/managing_imports/.gitignore
  example/managing_imports/README.md
  example/managing_imports/analysis_options.yaml
  example/managing_imports/bin/managing_imports.dart
  example/managing_imports/lib/functional.dart
  example/managing_imports/pubspec.lock
  example/managing_imports/pubspec.yaml
Labels: documentation, how to do that

#88 feat: Option.flatMapNullable
  lib/src/option.dart
  test/src/option_test.dart
Labels: enhancement

#90 feat: add extract and extractMap
  lib/src/map_extension.dart
  test/src/map_extension_test.dart
Labels: enhancement

#87 refactor: improve fromJson support
  lib/src/option.dart
  test/src/option_test.dart
Labels: enhancement

#89 feat: Option.flatMapThrowable
  lib/src/option.dart
  test/src/option_test.dart
Labels: enhancement
