Repository SandroMaglione/fpdart, pull requests merged in 2023-05, with the labels that each got.

#99 Update pokeapi example to riverpod v2
  .gitattributes
  example/pokeapi_functional/README.md
  example/pokeapi_functional/lib/api/fetch_pokemon.dart
  example/pokeapi_functional/lib/controllers/pokemon_provider.dart
  example/pokeapi_functional/lib/main.dart
  example/pokeapi_functional/lib/models/pokemon.dart
  example/pokeapi_functional/lib/models/pokemon.freezed.dart
  example/pokeapi_functional/lib/models/sprite.dart
  example/pokeapi_functional/lib/models/sprite.freezed.dart
  example/pokeapi_functional/lib/unions/request_status.dart
  example/pokeapi_functional/lib/unions/request_status.freezed.dart
  example/pokeapi_functional/pubspec.lock
  example/pokeapi_functional/pubspec.yaml
Labels: documentation, refactoring

#106 v0.6.0
  README.md
  packages/fpdart/CHANGELOG.md
  packages/fpdart/README.md
  packages/fpdart/example/screenshot_fpdart.png
  packages/fpdart/pubspec.yaml
  packages/fpdart_lint/README.md
  packages/fpdart_test/README.md
Labels: documentation

#110 Extensions and conversions to `Option` and `Either`
  packages/fpdart/CHANGELOG.md
  packages/fpdart/example/src/function/curry.dart
  packages/fpdart/example/src/function/identity.dart
  packages/fpdart/example/src/map/overview.dart
  packages/fpdart/lib/fpdart.dart
  packages/fpdart/lib/src/boolean.dart
  packages/fpdart/lib/src/compose.dart
  packages/fpdart/lib/src/date.dart
  packages/fpdart/lib/src/either.dart
  packages/fpdart/lib/src/extension/compose_extension.dart
  packages/fpdart/lib/src/extension/curry_extension.dart
  packages/fpdart/lib/src/extension/date_time_extension.dart
  packages/fpdart/lib/src/extension/extension.export.dart
  packages/fpdart/lib/src/extension/list_extension.dart
  packages/fpdart/lib/src/extension/map_extension.dart
  packages/fpdart/lib/src/extension/nullable_extension.dart
  packages/fpdart/lib/src/extension/option_extension.dart
  packages/fpdart/lib/src/extension/string_extension.dart
  packages/fpdart/lib/src/function.dart
  packages/fpdart/lib/src/io_option.dart
  packages/fpdart/lib/src/io_ref.dart
  packages/fpdart/lib/src/option.dart
  packages/fpdart/lib/src/task.dart
  packages/fpdart/lib/src/task_option.dart
  packages/fpdart/lib/src/tuple.dart
  packages/fpdart/lib/src/typeclass/foldable.dart
  packages/fpdart/lib/src/typeclass/monoid.dart
  packages/fpdart/lib/src/typedef.dart
  packages/fpdart/test/src/boolean_test.dart
  packages/fpdart/test/src/date_test.dart
  packages/fpdart/test/src/extension/curry_extension_test.dart
  packages/fpdart/test/src/extension/date_time_extension_test.dart
  packages/fpdart/test/src/extension/list_extension_test.dart
  packages/fpdart/test/src/extension/map_extension_test.dart
  packages/fpdart/test/src/extension/nullable_extension_test.dart
  packages/fpdart/test/src/extension/option_extension_test.dart
  packages/fpdart/test/src/extension/string_extension_test.dart
  packages/fpdart/test/src/function_test.dart
  packages/fpdart/test/src/option_test.dart
Labels: enhancement, refactoring

#114 Fix missing "s" in url path to display examples
  packages/fpdart/README.md
Labels: documentation

#122 README: Fix links
  packages/fpdart/README.md
Labels: documentation
